name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: push
jobs:
  set_env:
    runs-on:  ubuntu-latest
    steps:  
      - name: set set_env
        run:  echo "MY_ENV_VAR=9788" >> $GITHUB_ENV

      - name: use env
        run:  echo "the value of ENV variable is $MY_ENV_VAR"