name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    paths:
      - '!*.txt'
      - 'mac-app/**'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered on branch foo/bar"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: echo "foo/bar/master branch"

